name: libcommon
version: 1.91.1
main: aliuly\loader\Main
api: [1.12.0,2.0.0]
load: STARTUP

description: aliuly's common library
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/libcommon

commands:
  libcommon:
    description: Show libcommon version
    usage: "/libcommon"
    aliases: [lc]
    permission: libcommon.command

permissions:
  libcommon.command:
    default: true
    description: "libcommon command"
